### ISSUE TITLE
Resulting executable with --ignore-trailer doesn't run

### ISSUE THREAD

**Issue by davidfraser** [avast/pe_tools#6]
I have a large (785MB) executable that is a WiX-generated bootstrapper for a number of msi files. I want to edit the version info's File Description for this executable.

`peresed` works nicely for doing this, as long as the length of the string doesn't increase beyond 151 characters. If it does, the executable will no longer run at all. However, viewing the properties of the file you can see that the string has been set correctly.

**Comment by avakar** [comment]
Hi, can you link me to the executable a provide the precise command line you use?
